# Generated by Django 3.0.10 on 2020-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='pictures/blog-post-thumb-1.jpg', upload_to='pictures'),
        ),
    ]
