# Generated by Django 3.0.10 on 2020-09-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish', '-created')},
        ),
        migrations.AddField(
            model_name='post',
            name='read_length',
            field=models.IntegerField(default=4),
        ),
    ]
